{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "kube-keepalived-vip.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "kube-keepalived-vip.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - endpoints
  - services
  - configmaps
  verbs:
  - get
  - list
  - watch
{{- end -}}
