apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "kube-keepalived-vip.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "kube-keepalived-vip.fullname" . }}
data:
{{ toYaml .Values.services | indent 2 }}
